version: '3.4'

services:
  signalrsampleservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:DefaultConnection=Server=34.245.227.140; Port=5432; Database=gps_tracker; Username=postgres; Password=patrikduch07041993"
    ports:
      - "80"

