version: '3.4'

services:
  signalrsampleservice:
    image: ${DOCKER_REGISTRY-}signalrsampleservice
    build:
      context: .
      dockerfile: SignalRSampleService/Dockerfile
    networks:
      - app-network
  
  database:
    image: "postgres" # use latest official postgres version
    env_file:
      - ./config/postgres.env # configure postgres
    volumes:
      - databasedata:/var/lib/postgre/data/ # persist data even
    ports: 
     - 5432:5432 
    networks:
      - app-network

  adminer: # administration for postgre database
    image: adminer:latest
    environment: 
      ADMINER_DEFAULT_SERVER: database
    ports: 
     - 8080:8080
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: local-rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    networks:
      - app-network
networks:
  app-network:
    driver: bridge

volumes:
  databasedata:
  rabbitmqdata:
